from dragonfly import Choice

def letterChoice(name="letter"):
    return Choice(name, {
        'arch': 'a',
        'brov': 'b',
        'char': 'c',
        'delta': 'd',
        'echo': 'e',
        'foxy': 'f',
        'goof': 'g',
        'hotel': 'h',
        'india': 'i',
        'julia': 'j',
        'kilo': 'k',
        'lima': 'l',
        'mike': 'm',
        'novakeen': 'n',
        'oscar': 'o',
        'prime': 'p',
        'quebec': 'q',
        'romeo': 'r',
        'sierra': 's',
        'tango': 't',
        'uniform': 'u',
        'victor': 'v',
        'whiskey': 'w',
        'x-ray': 'x',
        'yankee': 'y',
        'zulu': 'z',

        'big arch': 'A',
        'big brov': 'B',
        'big char': 'C',
        'big delta': 'D',
        'big echo': 'E',
        'big foxy': 'F',
        'big goof': 'G',
        'big hotel': 'H',
        'big india': 'I',
        'big julia': 'J',
        'big kilo': 'K',
        'big lima': 'L',
        'big mike': 'M',
        'big novakeen': 'N',
        'big oscar': 'O',
        'big prime': 'P',
        'big quebec': 'Q',
        'big romeo': 'R',
        'big sierra': 'S',
        'big tango': 'T',
        'big uniform': 'U',
        'big victor': 'V',
        'big whiskey': 'W',
        'big x-ray': 'X',
        'big yankee': 'Y',
        'big zulu': 'Z',

        'zero': '0',
        'one': '1',
        'two': '2',
        'three': '3',
        'four': '4',
        'five': '5',
        'six': '6',
        'seven': '7',
        'eight': '8',
        'nine': '9',

        'ace': 'space',
        'tabby': 'tab',

        'ampersand': 'ampersand',
        '(apostrophe | chicky)': 'apostrophe',
        'single quote': 'squote',
        '(asterisk | starling)': 'asterisk',
        'at': 'at',
        'backslash': 'backslash',
        '(backtick | ticky)': 'backtick',
        'pipe': 'bar',
        '(caret | carrot)': 'caret',
        'deckle': 'colon',
        'comma': 'comma',
        '(dollar | dolly)': 'dollar',
        '(dot|period)': 'dot',
        'chocky': 'dquote',
        'equal': 'equal',
        'clamor': 'exclamation',
        'hashtag': 'hash',
        'hyphen': 'hyphen',
        'minus': 'minus',
        'modulo': 'percent',
        'plus': 'plus',
        'questo': 'question',
        'semper': 'semicolon',
        'slash': 'slash',
        'tilde': 'tilde',
        '(underscore | score)': 'underscore',

        'langle': 'langle',
        'lace': 'lbrace',
        'lack': 'lbracket',
        'laip': 'lparen',
        'rangle': 'rangle',
        'race': 'rbrace',
        'rack': 'rbracket',
        'raip': 'rparen',
        })
